services:
  api:
    build:
      # use the `base` multi-stage... stage
      target: base
    # run this command after finishing base stage
    command: npm run dev:local  
    # connect local src to containers src folder
    volumes:
      - ./src:${DOCKER_WORKDIR}/src
      - ./package.json:${DOCKER_WORKDIR}/package.json
      - ./package-lock.json:${DOCKER_WORKDIR}/package-lock.json
      - ./tsconfig.json:${DOCKER_WORKDIR}/tsconfig.json